version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.11.2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: dist
          paths: [.]

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: dist
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm run bump-version
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master

  build-and-deploy:
    jobs:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: fix-quicktype